### ISSUE TITLE
Update netlify bits of travis.yml

### ISSUE THREAD

**Issue by jennybc** [tidyverse/principles#32]
The `.travis.yml` file here needs an update for the new netlify CLI.

Before/current:
```
deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
```

After needs to look more like Advanced R:
```
deploy:
  provider: script
  script: netlify deploy --prod --dir _book
  skip_cleanup: true
```

and there's the **hidden assumption** that the netlify pat has been stored as an encrypted env var named `NETLIFY_AUTH_TOKEN` on travis.

Auto-build-and-deploy will be broken until we do this.
